### ISSUE TITLE
direct git clone not possible

### ISSUE THREAD

**Issue by WolfgangFahl** [PascalNoisette/mediawiki-extensions-Slides#2]
```
git clone https://github.com/PascalNoisette/mediawiki-extensions-Slides
```
will not work:
```
[Thu Mar 11 09:23:46.993615 2021] [php7:notice] [pid 3554541] [client 78.46.161.81:37058] PHP Fatal error:  Uncaught Exception: Unable to open file /var/www/mediawiki/mediawiki-1.35.0/extensions/Slides/extension.json
```
```
git clone https://github.com/PascalNoisette/mediawiki-extensions-Slides Slides
```
is necessary.
I'd recommend to name the github repository just like the extension and give the extension a more specific name than just "Slides" e.g. "Reveal-Slides"

**Comment by PascalNoisette** [comment]
If this module reach a point where it's worth to be published at https://www.mediawiki.org/, it can be rename indeed. I will keeo that in mind for later.

**Comment by WolfgangFahl** [comment]
For the time being https://www.mediawiki.org/wiki/Extension:Slides is a stub
